version: '3.8'

services:
  app:
    container_name: aiphoria_audio_converter
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5000:5000
    # networks:
      # - aiphoria_network
      # - aiphoria_network_dev
networks:
  aiphoria_network_dev:
    external: true 
  aiphoria_network:
    external: true
    
